development: &defaults
  adapter: mysql2
  encoding: utf8
  database: tradenaira_blogo
  username: root
  password: root
  pool: 5
  # reconnect: true
  socket: '/tmp/mysql.sock'
  host: 127.0.0.1

test:
  <<: *defaults
  database: tradenaira_blogo_test

production:
  <<: *defaults
  database: tradenaira_blogo_production

development:
  <<: *defaults
  database: tradenaira_blogo_development